name: Instrumented Test

on:
  pull_request:
    branches: [ start ]

jobs:
  run-test:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.17.0
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
